services:
  app:
    user: "${UID}:${GID}"
    build: 
      context: .
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    env_file:
      - .env
    volumes:
      - .:/app
      - gem_cache:/gems
    tty: true
    stdin_open: true   
volumes:
  gem_cache:
